/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import sk.emaa.model.entity.tables.Attendance;
import sk.emaa.model.entity.tables.School;
import sk.emaa.model.entity.tables.Student;
import sk.emaa.model.entity.tables.Training;
import sk.emaa.model.entity.tables.User;
import sk.emaa.model.entity.tables.records.AttendanceRecord;
import sk.emaa.model.entity.tables.records.SchoolRecord;
import sk.emaa.model.entity.tables.records.StudentRecord;
import sk.emaa.model.entity.tables.records.TrainingRecord;
import sk.emaa.model.entity.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AttendanceRecord> ATTENDANCES_PKEY = Internal.createUniqueKey(Attendance.ATTENDANCE, DSL.name("attendances_pkey"), new TableField[] { Attendance.ATTENDANCE.ID }, true);
    public static final UniqueKey<SchoolRecord> SCHOOL_PKEY = Internal.createUniqueKey(School.SCHOOL, DSL.name("school_pkey"), new TableField[] { School.SCHOOL.ID }, true);
    public static final UniqueKey<StudentRecord> STUDENTS_PKEY = Internal.createUniqueKey(Student.STUDENT, DSL.name("students_pkey"), new TableField[] { Student.STUDENT.ID }, true);
    public static final UniqueKey<TrainingRecord> TRAINING_PKEY = Internal.createUniqueKey(Training.TRAINING, DSL.name("training_pkey"), new TableField[] { Training.TRAINING.ID }, true);
    public static final UniqueKey<UserRecord> USERS_PKEY = Internal.createUniqueKey(User.USER, DSL.name("users_pkey"), new TableField[] { User.USER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AttendanceRecord, StudentRecord> ATTENDANCE__ATTENDANCES_STUDENT_ID_FKEY = Internal.createForeignKey(Attendance.ATTENDANCE, DSL.name("attendances_student_id_fkey"), new TableField[] { Attendance.ATTENDANCE.STUDENT_ID }, Keys.STUDENTS_PKEY, new TableField[] { Student.STUDENT.ID }, true);
    public static final ForeignKey<AttendanceRecord, TrainingRecord> ATTENDANCE__ATTENDANCES_TRAINING_ID_FKEY = Internal.createForeignKey(Attendance.ATTENDANCE, DSL.name("attendances_training_id_fkey"), new TableField[] { Attendance.ATTENDANCE.TRAINING_ID }, Keys.TRAINING_PKEY, new TableField[] { Training.TRAINING.ID }, true);
    public static final ForeignKey<StudentRecord, SchoolRecord> STUDENT__STUDENTS_SCHOOL_ID_FKEY = Internal.createForeignKey(Student.STUDENT, DSL.name("students_school_id_fkey"), new TableField[] { Student.STUDENT.SCHOOL_ID }, Keys.SCHOOL_PKEY, new TableField[] { School.SCHOOL.ID }, true);
    public static final ForeignKey<TrainingRecord, SchoolRecord> TRAINING__TRAINING_SCHOOL_ID_FKEY = Internal.createForeignKey(Training.TRAINING, DSL.name("training_school_id_fkey"), new TableField[] { Training.TRAINING.SCHOOL_ID }, Keys.SCHOOL_PKEY, new TableField[] { School.SCHOOL.ID }, true);
    public static final ForeignKey<UserRecord, SchoolRecord> USER__USERS_SCHOOL_ID_FKEY = Internal.createForeignKey(User.USER, DSL.name("users_school_id_fkey"), new TableField[] { User.USER.SCHOOL_ID }, Keys.SCHOOL_PKEY, new TableField[] { School.SCHOOL.ID }, true);
}
