/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sk.emaa.model.entity.tables.Attendance;
import sk.emaa.model.entity.tables.CreditTransaction;
import sk.emaa.model.entity.tables.School;
import sk.emaa.model.entity.tables.Student;
import sk.emaa.model.entity.tables.Training;
import sk.emaa.model.entity.tables.UserAccount;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.attendance</code>.
     */
    public final Attendance ATTENDANCE = Attendance.ATTENDANCE;

    /**
     * The table <code>public.credit_transaction</code>.
     */
    public final CreditTransaction CREDIT_TRANSACTION = CreditTransaction.CREDIT_TRANSACTION;

    /**
     * The table <code>public.school</code>.
     */
    public final School SCHOOL = School.SCHOOL;

    /**
     * The table <code>public.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.training</code>.
     */
    public final Training TRAINING = Training.TRAINING;

    /**
     * The table <code>public.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.USERS_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Attendance.ATTENDANCE,
            CreditTransaction.CREDIT_TRANSACTION,
            School.SCHOOL,
            Student.STUDENT,
            Training.TRAINING,
            UserAccount.USER_ACCOUNT
        );
    }
}
