/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sk.emaa.model.entity.tables.Attendance;
import sk.emaa.model.entity.tables.CreditTransaction;
import sk.emaa.model.entity.tables.MartialArt;
import sk.emaa.model.entity.tables.Role;
import sk.emaa.model.entity.tables.School;
import sk.emaa.model.entity.tables.Student;
import sk.emaa.model.entity.tables.StudentMartialArt;
import sk.emaa.model.entity.tables.StudentType;
import sk.emaa.model.entity.tables.Training;
import sk.emaa.model.entity.tables.UserAccount;
import sk.emaa.model.entity.tables.UserRole;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.attendance</code>.
     */
    public final Attendance ATTENDANCE = Attendance.ATTENDANCE;

    /**
     * The table <code>public.credit_transaction</code>.
     */
    public final CreditTransaction CREDIT_TRANSACTION = CreditTransaction.CREDIT_TRANSACTION;

    /**
     * The table <code>public.martial_art</code>.
     */
    public final MartialArt MARTIAL_ART = MartialArt.MARTIAL_ART;

    /**
     * The table <code>public.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.school</code>.
     */
    public final School SCHOOL = School.SCHOOL;

    /**
     * The table <code>public.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.student_martial_art</code>.
     */
    public final StudentMartialArt STUDENT_MARTIAL_ART = StudentMartialArt.STUDENT_MARTIAL_ART;

    /**
     * The table <code>public.student_type</code>.
     */
    public final StudentType STUDENT_TYPE = StudentType.STUDENT_TYPE;

    /**
     * The table <code>public.training</code>.
     */
    public final Training TRAINING = Training.TRAINING;

    /**
     * The table <code>public.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>public.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Attendance.ATTENDANCE,
            CreditTransaction.CREDIT_TRANSACTION,
            MartialArt.MARTIAL_ART,
            Role.ROLE,
            School.SCHOOL,
            Student.STUDENT,
            StudentMartialArt.STUDENT_MARTIAL_ART,
            StudentType.STUDENT_TYPE,
            Training.TRAINING,
            UserAccount.USER_ACCOUNT,
            UserRole.USER_ROLE
        );
    }
}
