/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity;


import sk.emaa.model.entity.tables.Attendance;
import sk.emaa.model.entity.tables.CreditTransaction;
import sk.emaa.model.entity.tables.School;
import sk.emaa.model.entity.tables.Student;
import sk.emaa.model.entity.tables.Training;
import sk.emaa.model.entity.tables.UserAccount;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.attendance</code>.
     */
    public static final Attendance ATTENDANCE = Attendance.ATTENDANCE;

    /**
     * The table <code>public.credit_transaction</code>.
     */
    public static final CreditTransaction CREDIT_TRANSACTION = CreditTransaction.CREDIT_TRANSACTION;

    /**
     * The table <code>public.school</code>.
     */
    public static final School SCHOOL = School.SCHOOL;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.training</code>.
     */
    public static final Training TRAINING = Training.TRAINING;

    /**
     * The table <code>public.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;
}
