/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity;


import sk.emaa.model.entity.tables.Attendance;
import sk.emaa.model.entity.tables.CreditTransaction;
import sk.emaa.model.entity.tables.FlywaySchemaHistory;
import sk.emaa.model.entity.tables.MartialArt;
import sk.emaa.model.entity.tables.Role;
import sk.emaa.model.entity.tables.School;
import sk.emaa.model.entity.tables.Student;
import sk.emaa.model.entity.tables.StudentMartialArt;
import sk.emaa.model.entity.tables.StudentType;
import sk.emaa.model.entity.tables.Training;
import sk.emaa.model.entity.tables.UserAccount;
import sk.emaa.model.entity.tables.UserRole;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.attendance</code>.
     */
    public static final Attendance ATTENDANCE = Attendance.ATTENDANCE;

    /**
     * The table <code>public.credit_transaction</code>.
     */
    public static final CreditTransaction CREDIT_TRANSACTION = CreditTransaction.CREDIT_TRANSACTION;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.martial_art</code>.
     */
    public static final MartialArt MARTIAL_ART = MartialArt.MARTIAL_ART;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.school</code>.
     */
    public static final School SCHOOL = School.SCHOOL;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.student_martial_art</code>.
     */
    public static final StudentMartialArt STUDENT_MARTIAL_ART = StudentMartialArt.STUDENT_MARTIAL_ART;

    /**
     * The table <code>public.student_type</code>.
     */
    public static final StudentType STUDENT_TYPE = StudentType.STUDENT_TYPE;

    /**
     * The table <code>public.training</code>.
     */
    public static final Training TRAINING = Training.TRAINING;

    /**
     * The table <code>public.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>public.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
