/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sk.emaa.model.entity.tables.Attendance;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttendanceRecord extends UpdatableRecordImpl<AttendanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.attendance.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.attendance.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.attendance.student_id</code>.
     */
    public void setStudentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.attendance.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.attendance.training_id</code>.
     */
    public void setTrainingId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.attendance.training_id</code>.
     */
    public Integer getTrainingId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.attendance.present</code>.
     */
    public void setPresent(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.attendance.present</code>.
     */
    public Boolean getPresent() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttendanceRecord
     */
    public AttendanceRecord() {
        super(Attendance.ATTENDANCE);
    }

    /**
     * Create a detached, initialised AttendanceRecord
     */
    public AttendanceRecord(Integer id, Integer studentId, Integer trainingId, Boolean present) {
        super(Attendance.ATTENDANCE);

        setId(id);
        setStudentId(studentId);
        setTrainingId(trainingId);
        setPresent(present);
        resetChangedOnNotNull();
    }
}
