/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sk.emaa.model.entity.tables.CreditTransaction;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CreditTransactionRecord extends UpdatableRecordImpl<CreditTransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.credit_transaction.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.credit_transaction.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.credit_transaction.student_id</code>.
     */
    public void setStudentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.credit_transaction.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.credit_transaction.amount</code>.
     */
    public void setAmount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.credit_transaction.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.credit_transaction.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.credit_transaction.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.credit_transaction.payment_type</code>.
     */
    public void setPaymentType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.credit_transaction.payment_type</code>.
     */
    public String getPaymentType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.credit_transaction.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.credit_transaction.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CreditTransactionRecord
     */
    public CreditTransactionRecord() {
        super(CreditTransaction.CREDIT_TRANSACTION);
    }

    /**
     * Create a detached, initialised CreditTransactionRecord
     */
    public CreditTransactionRecord(Integer id, Integer studentId, Integer amount, String description, String paymentType, LocalDateTime createdAt) {
        super(CreditTransaction.CREDIT_TRANSACTION);

        setId(id);
        setStudentId(studentId);
        setAmount(amount);
        setDescription(description);
        setPaymentType(paymentType);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
