/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sk.emaa.model.entity.tables.MartialArt;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MartialArtRecord extends UpdatableRecordImpl<MartialArtRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.martial_art.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.martial_art.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.martial_art.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.martial_art.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.martial_art.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.martial_art.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.martial_art.program_type</code>.
     */
    public void setProgramType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.martial_art.program_type</code>.
     */
    public String getProgramType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.martial_art.variant</code>.
     */
    public void setVariant(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.martial_art.variant</code>.
     */
    public String getVariant() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.martial_art.school_id</code>.
     */
    public void setSchoolId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.martial_art.school_id</code>.
     */
    public Integer getSchoolId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.martial_art.active</code>.
     */
    public void setActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.martial_art.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.martial_art.credit_payment</code>.
     */
    public void setCreditPayment(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.martial_art.credit_payment</code>.
     */
    public Integer getCreditPayment() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.martial_art.monthly_payment</code>.
     */
    public void setMonthlyPayment(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.martial_art.monthly_payment</code>.
     */
    public Integer getMonthlyPayment() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.martial_art.yearly_payment</code>.
     */
    public void setYearlyPayment(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.martial_art.yearly_payment</code>.
     */
    public Integer getYearlyPayment() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.martial_art.color</code>.
     */
    public void setColor(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.martial_art.color</code>.
     */
    public String getColor() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MartialArtRecord
     */
    public MartialArtRecord() {
        super(MartialArt.MARTIAL_ART);
    }

    /**
     * Create a detached, initialised MartialArtRecord
     */
    public MartialArtRecord(Integer id, String code, String name, String programType, String variant, Integer schoolId, Boolean active, Integer creditPayment, Integer monthlyPayment, Integer yearlyPayment, String color) {
        super(MartialArt.MARTIAL_ART);

        setId(id);
        setCode(code);
        setName(name);
        setProgramType(programType);
        setVariant(variant);
        setSchoolId(schoolId);
        setActive(active);
        setCreditPayment(creditPayment);
        setMonthlyPayment(monthlyPayment);
        setYearlyPayment(yearlyPayment);
        setColor(color);
        resetChangedOnNotNull();
    }
}
