/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sk.emaa.model.entity.tables.School;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SchoolRecord extends UpdatableRecordImpl<SchoolRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.school.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.school.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.school.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.school.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.school.address</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.school.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.school.credit_payment</code>.
     */
    public void setCreditPayment(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.school.credit_payment</code>.
     */
    public Integer getCreditPayment() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.school.monthly_payment</code>.
     */
    public void setMonthlyPayment(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.school.monthly_payment</code>.
     */
    public Integer getMonthlyPayment() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.school.yearly_payment</code>.
     */
    public void setYearlyPayment(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.school.yearly_payment</code>.
     */
    public Integer getYearlyPayment() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchoolRecord
     */
    public SchoolRecord() {
        super(School.SCHOOL);
    }

    /**
     * Create a detached, initialised SchoolRecord
     */
    public SchoolRecord(Integer id, String name, String address, Integer creditPayment, Integer monthlyPayment, Integer yearlyPayment) {
        super(School.SCHOOL);

        setId(id);
        setName(name);
        setAddress(address);
        setCreditPayment(creditPayment);
        setMonthlyPayment(monthlyPayment);
        setYearlyPayment(yearlyPayment);
        resetChangedOnNotNull();
    }
}
