/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sk.emaa.model.entity.tables.StudentType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StudentTypeRecord extends UpdatableRecordImpl<StudentTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.student_type.code</code>.
     */
    public void setCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.student_type.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.student_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.student_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentTypeRecord
     */
    public StudentTypeRecord() {
        super(StudentType.STUDENT_TYPE);
    }

    /**
     * Create a detached, initialised StudentTypeRecord
     */
    public StudentTypeRecord(String code, String name) {
        super(StudentType.STUDENT_TYPE);

        setCode(code);
        setName(name);
        resetChangedOnNotNull();
    }
}
