/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables.records;


import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sk.emaa.model.entity.tables.Student;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.student.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.student.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.student.firstname</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.student.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.student.lastname</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.student.lastname</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.student.gender</code>.
     */
    public void setGender(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.student.gender</code>.
     */
    public String getGender() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.student.id_card</code>.
     */
    public void setIdCard(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.student.id_card</code>.
     */
    public String getIdCard() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.student.street</code>.
     */
    public void setStreet(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.student.street</code>.
     */
    public String getStreet() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.student.street_no</code>.
     */
    public void setStreetNo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.student.street_no</code>.
     */
    public String getStreetNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.student.city</code>.
     */
    public void setCity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.student.city</code>.
     */
    public String getCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.student.zip_code</code>.
     */
    public void setZipCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.student.zip_code</code>.
     */
    public String getZipCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.student.mobil</code>.
     */
    public void setMobil(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.student.mobil</code>.
     */
    public String getMobil() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.student.email</code>.
     */
    public void setEmail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.student.email</code>.
     */
    public String getEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.student.school_id</code>.
     */
    public void setSchoolId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.student.school_id</code>.
     */
    public Integer getSchoolId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.student.vegetarian</code>.
     */
    public void setVegetarian(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.student.vegetarian</code>.
     */
    public Boolean getVegetarian() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.student.active</code>.
     */
    public void setActive(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.student.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.student.credit</code>.
     */
    public void setCredit(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.student.credit</code>.
     */
    public Integer getCredit() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.student.birthdate</code>.
     */
    public void setBirthdate(LocalDate value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.student.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return (LocalDate) get(15);
    }

    /**
     * Setter for <code>public.student.payment_type</code>.
     */
    public void setPaymentType(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.student.payment_type</code>.
     */
    public String getPaymentType() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer id, String firstname, String lastname, String gender, String idCard, String street, String streetNo, String city, String zipCode, String mobil, String email, Integer schoolId, Boolean vegetarian, Boolean active, Integer credit, LocalDate birthdate, String paymentType) {
        super(Student.STUDENT);

        setId(id);
        setFirstname(firstname);
        setLastname(lastname);
        setGender(gender);
        setIdCard(idCard);
        setStreet(street);
        setStreetNo(streetNo);
        setCity(city);
        setZipCode(zipCode);
        setMobil(mobil);
        setEmail(email);
        setSchoolId(schoolId);
        setVegetarian(vegetarian);
        setActive(active);
        setCredit(credit);
        setBirthdate(birthdate);
        setPaymentType(paymentType);
        resetChangedOnNotNull();
    }
}
