/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import sk.emaa.model.entity.tables.StudentMartialArt;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StudentMartialArtRecord extends UpdatableRecordImpl<StudentMartialArtRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.student_martial_art.student_id</code>.
     */
    public void setStudentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.student_martial_art.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.student_martial_art.martial_art_id</code>.
     */
    public void setMartialArtId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.student_martial_art.martial_art_id</code>.
     */
    public Integer getMartialArtId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.student_martial_art.active</code>.
     */
    public void setActive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.student_martial_art.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.student_martial_art.grade</code>.
     */
    public void setGrade(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.student_martial_art.grade</code>.
     */
    public Integer getGrade() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.student_martial_art.base_payment_amount</code>.
     */
    public void setBasePaymentAmount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.student_martial_art.base_payment_amount</code>.
     */
    public Integer getBasePaymentAmount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.student_martial_art.payment_type</code>.
     */
    public void setPaymentType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.student_martial_art.payment_type</code>.
     */
    public String getPaymentType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.student_martial_art.credit</code>.
     */
    public void setCredit(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.student_martial_art.credit</code>.
     */
    public Integer getCredit() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentMartialArtRecord
     */
    public StudentMartialArtRecord() {
        super(StudentMartialArt.STUDENT_MARTIAL_ART);
    }

    /**
     * Create a detached, initialised StudentMartialArtRecord
     */
    public StudentMartialArtRecord(Integer studentId, Integer martialArtId, Boolean active, Integer grade, Integer basePaymentAmount, String paymentType, Integer credit) {
        super(StudentMartialArt.STUDENT_MARTIAL_ART);

        setStudentId(studentId);
        setMartialArtId(martialArtId);
        setActive(active);
        setGrade(grade);
        setBasePaymentAmount(basePaymentAmount);
        setPaymentType(paymentType);
        setCredit(credit);
        resetChangedOnNotNull();
    }
}
