/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables.records;


import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sk.emaa.model.entity.tables.Training;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrainingRecord extends UpdatableRecordImpl<TrainingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.training.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.training.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.training.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.training.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.training.school_id</code>.
     */
    public void setSchoolId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.training.school_id</code>.
     */
    public Integer getSchoolId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrainingRecord
     */
    public TrainingRecord() {
        super(Training.TRAINING);
    }

    /**
     * Create a detached, initialised TrainingRecord
     */
    public TrainingRecord(Integer id, LocalDate date, Integer schoolId) {
        super(Training.TRAINING);

        setId(id);
        setDate(date);
        setSchoolId(schoolId);
        resetChangedOnNotNull();
    }
}
