/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.Student.StudentPath;
import sk.emaa.model.entity.tables.Training.TrainingPath;
import sk.emaa.model.entity.tables.records.AttendanceRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Attendance extends TableImpl<AttendanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.attendance</code>
     */
    public static final Attendance ATTENDANCE = new Attendance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AttendanceRecord> getRecordType() {
        return AttendanceRecord.class;
    }

    /**
     * The column <code>public.attendance.id</code>.
     */
    public final TableField<AttendanceRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.attendance.student_id</code>.
     */
    public final TableField<AttendanceRecord, Integer> STUDENT_ID = createField(DSL.name("student_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.attendance.training_id</code>.
     */
    public final TableField<AttendanceRecord, Integer> TRAINING_ID = createField(DSL.name("training_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.attendance.created_at</code>.
     */
    public final TableField<AttendanceRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Attendance(Name alias, Table<AttendanceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Attendance(Name alias, Table<AttendanceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.attendance</code> table reference
     */
    public Attendance(String alias) {
        this(DSL.name(alias), ATTENDANCE);
    }

    /**
     * Create an aliased <code>public.attendance</code> table reference
     */
    public Attendance(Name alias) {
        this(alias, ATTENDANCE);
    }

    /**
     * Create a <code>public.attendance</code> table reference
     */
    public Attendance() {
        this(DSL.name("attendance"), null);
    }

    public <O extends Record> Attendance(Table<O> path, ForeignKey<O, AttendanceRecord> childPath, InverseForeignKey<O, AttendanceRecord> parentPath) {
        super(path, childPath, parentPath, ATTENDANCE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AttendancePath extends Attendance implements Path<AttendanceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AttendancePath(Table<O> path, ForeignKey<O, AttendanceRecord> childPath, InverseForeignKey<O, AttendanceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AttendancePath(Name alias, Table<AttendanceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AttendancePath as(String alias) {
            return new AttendancePath(DSL.name(alias), this);
        }

        @Override
        public AttendancePath as(Name alias) {
            return new AttendancePath(alias, this);
        }

        @Override
        public AttendancePath as(Table<?> alias) {
            return new AttendancePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AttendanceRecord, Integer> getIdentity() {
        return (Identity<AttendanceRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AttendanceRecord> getPrimaryKey() {
        return Keys.ATTENDANCE_PKEY;
    }

    @Override
    public List<ForeignKey<AttendanceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ATTENDANCE__ATTENDANCE_STUDENT_ID_FKEY, Keys.ATTENDANCE__ATTENDANCE_TRAINING_ID_FKEY);
    }

    private transient StudentPath _student;

    /**
     * Get the implicit join path to the <code>public.student</code> table.
     */
    public StudentPath student() {
        if (_student == null)
            _student = new StudentPath(this, Keys.ATTENDANCE__ATTENDANCE_STUDENT_ID_FKEY, null);

        return _student;
    }

    private transient TrainingPath _training;

    /**
     * Get the implicit join path to the <code>public.training</code> table.
     */
    public TrainingPath training() {
        if (_training == null)
            _training = new TrainingPath(this, Keys.ATTENDANCE__ATTENDANCE_TRAINING_ID_FKEY, null);

        return _training;
    }

    @Override
    public Attendance as(String alias) {
        return new Attendance(DSL.name(alias), this);
    }

    @Override
    public Attendance as(Name alias) {
        return new Attendance(alias, this);
    }

    @Override
    public Attendance as(Table<?> alias) {
        return new Attendance(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Attendance rename(String name) {
        return new Attendance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Attendance rename(Name name) {
        return new Attendance(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Attendance rename(Table<?> name) {
        return new Attendance(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attendance where(Condition condition) {
        return new Attendance(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attendance where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attendance where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attendance where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Attendance where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Attendance where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Attendance where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Attendance where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attendance whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Attendance whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
