/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.Student.StudentPath;
import sk.emaa.model.entity.tables.records.CreditTransactionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CreditTransaction extends TableImpl<CreditTransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.credit_transaction</code>
     */
    public static final CreditTransaction CREDIT_TRANSACTION = new CreditTransaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CreditTransactionRecord> getRecordType() {
        return CreditTransactionRecord.class;
    }

    /**
     * The column <code>public.credit_transaction.id</code>.
     */
    public final TableField<CreditTransactionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.credit_transaction.student_id</code>.
     */
    public final TableField<CreditTransactionRecord, Integer> STUDENT_ID = createField(DSL.name("student_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.credit_transaction.amount</code>.
     */
    public final TableField<CreditTransactionRecord, Integer> AMOUNT = createField(DSL.name("amount"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.credit_transaction.description</code>.
     */
    public final TableField<CreditTransactionRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.credit_transaction.created_at</code>.
     */
    public final TableField<CreditTransactionRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private CreditTransaction(Name alias, Table<CreditTransactionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CreditTransaction(Name alias, Table<CreditTransactionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.credit_transaction</code> table reference
     */
    public CreditTransaction(String alias) {
        this(DSL.name(alias), CREDIT_TRANSACTION);
    }

    /**
     * Create an aliased <code>public.credit_transaction</code> table reference
     */
    public CreditTransaction(Name alias) {
        this(alias, CREDIT_TRANSACTION);
    }

    /**
     * Create a <code>public.credit_transaction</code> table reference
     */
    public CreditTransaction() {
        this(DSL.name("credit_transaction"), null);
    }

    public <O extends Record> CreditTransaction(Table<O> path, ForeignKey<O, CreditTransactionRecord> childPath, InverseForeignKey<O, CreditTransactionRecord> parentPath) {
        super(path, childPath, parentPath, CREDIT_TRANSACTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CreditTransactionPath extends CreditTransaction implements Path<CreditTransactionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CreditTransactionPath(Table<O> path, ForeignKey<O, CreditTransactionRecord> childPath, InverseForeignKey<O, CreditTransactionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CreditTransactionPath(Name alias, Table<CreditTransactionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CreditTransactionPath as(String alias) {
            return new CreditTransactionPath(DSL.name(alias), this);
        }

        @Override
        public CreditTransactionPath as(Name alias) {
            return new CreditTransactionPath(alias, this);
        }

        @Override
        public CreditTransactionPath as(Table<?> alias) {
            return new CreditTransactionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CreditTransactionRecord, Integer> getIdentity() {
        return (Identity<CreditTransactionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CreditTransactionRecord> getPrimaryKey() {
        return Keys.CREDIT_TRANSACTION_PKEY;
    }

    @Override
    public List<ForeignKey<CreditTransactionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CREDIT_TRANSACTION__CREDIT_TRANSACTION_STUDENT_ID_FKEY);
    }

    private transient StudentPath _student;

    /**
     * Get the implicit join path to the <code>public.student</code> table.
     */
    public StudentPath student() {
        if (_student == null)
            _student = new StudentPath(this, Keys.CREDIT_TRANSACTION__CREDIT_TRANSACTION_STUDENT_ID_FKEY, null);

        return _student;
    }

    @Override
    public CreditTransaction as(String alias) {
        return new CreditTransaction(DSL.name(alias), this);
    }

    @Override
    public CreditTransaction as(Name alias) {
        return new CreditTransaction(alias, this);
    }

    @Override
    public CreditTransaction as(Table<?> alias) {
        return new CreditTransaction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CreditTransaction rename(String name) {
        return new CreditTransaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CreditTransaction rename(Name name) {
        return new CreditTransaction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CreditTransaction rename(Table<?> name) {
        return new CreditTransaction(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreditTransaction where(Condition condition) {
        return new CreditTransaction(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreditTransaction where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreditTransaction where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreditTransaction where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CreditTransaction where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CreditTransaction where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CreditTransaction where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CreditTransaction where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreditTransaction whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreditTransaction whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
