/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.CreditTransaction.CreditTransactionPath;
import sk.emaa.model.entity.tables.School.SchoolPath;
import sk.emaa.model.entity.tables.Student.StudentPath;
import sk.emaa.model.entity.tables.StudentMartialArt.StudentMartialArtPath;
import sk.emaa.model.entity.tables.Training.TrainingPath;
import sk.emaa.model.entity.tables.records.MartialArtRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MartialArt extends TableImpl<MartialArtRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.martial_art</code>
     */
    public static final MartialArt MARTIAL_ART = new MartialArt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MartialArtRecord> getRecordType() {
        return MartialArtRecord.class;
    }

    /**
     * The column <code>public.martial_art.id</code>.
     */
    public final TableField<MartialArtRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.martial_art.code</code>.
     */
    public final TableField<MartialArtRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.martial_art.name</code>.
     */
    public final TableField<MartialArtRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.martial_art.program_type</code>.
     */
    public final TableField<MartialArtRecord, String> PROGRAM_TYPE = createField(DSL.name("program_type"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.martial_art.variant</code>.
     */
    public final TableField<MartialArtRecord, String> VARIANT = createField(DSL.name("variant"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.martial_art.school_id</code>.
     */
    public final TableField<MartialArtRecord, Integer> SCHOOL_ID = createField(DSL.name("school_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.martial_art.active</code>.
     */
    public final TableField<MartialArtRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.martial_art.credit_payment</code>.
     */
    public final TableField<MartialArtRecord, Integer> CREDIT_PAYMENT = createField(DSL.name("credit_payment"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.martial_art.monthly_payment</code>.
     */
    public final TableField<MartialArtRecord, Integer> MONTHLY_PAYMENT = createField(DSL.name("monthly_payment"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.martial_art.yearly_payment</code>.
     */
    public final TableField<MartialArtRecord, Integer> YEARLY_PAYMENT = createField(DSL.name("yearly_payment"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.martial_art.color</code>.
     */
    public final TableField<MartialArtRecord, String> COLOR = createField(DSL.name("color"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("'brown'::character varying"), SQLDataType.VARCHAR)), this, "");

    private MartialArt(Name alias, Table<MartialArtRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MartialArt(Name alias, Table<MartialArtRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.martial_art</code> table reference
     */
    public MartialArt(String alias) {
        this(DSL.name(alias), MARTIAL_ART);
    }

    /**
     * Create an aliased <code>public.martial_art</code> table reference
     */
    public MartialArt(Name alias) {
        this(alias, MARTIAL_ART);
    }

    /**
     * Create a <code>public.martial_art</code> table reference
     */
    public MartialArt() {
        this(DSL.name("martial_art"), null);
    }

    public <O extends Record> MartialArt(Table<O> path, ForeignKey<O, MartialArtRecord> childPath, InverseForeignKey<O, MartialArtRecord> parentPath) {
        super(path, childPath, parentPath, MARTIAL_ART);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MartialArtPath extends MartialArt implements Path<MartialArtRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MartialArtPath(Table<O> path, ForeignKey<O, MartialArtRecord> childPath, InverseForeignKey<O, MartialArtRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MartialArtPath(Name alias, Table<MartialArtRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MartialArtPath as(String alias) {
            return new MartialArtPath(DSL.name(alias), this);
        }

        @Override
        public MartialArtPath as(Name alias) {
            return new MartialArtPath(alias, this);
        }

        @Override
        public MartialArtPath as(Table<?> alias) {
            return new MartialArtPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MartialArtRecord, Integer> getIdentity() {
        return (Identity<MartialArtRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MartialArtRecord> getPrimaryKey() {
        return Keys.MARTIAL_ART_PKEY;
    }

    @Override
    public List<UniqueKey<MartialArtRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MARTIAL_ART_CODE_SCHOOL_ID_KEY);
    }

    @Override
    public List<ForeignKey<MartialArtRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MARTIAL_ART__MARTIAL_ART_SCHOOL_ID_FKEY);
    }

    private transient SchoolPath _school;

    /**
     * Get the implicit join path to the <code>public.school</code> table.
     */
    public SchoolPath school() {
        if (_school == null)
            _school = new SchoolPath(this, Keys.MARTIAL_ART__MARTIAL_ART_SCHOOL_ID_FKEY, null);

        return _school;
    }

    private transient CreditTransactionPath _creditTransaction;

    /**
     * Get the implicit to-many join path to the
     * <code>public.credit_transaction</code> table
     */
    public CreditTransactionPath creditTransaction() {
        if (_creditTransaction == null)
            _creditTransaction = new CreditTransactionPath(this, null, Keys.CREDIT_TRANSACTION__CREDIT_TRANSACTION_MARTIAL_ART_ID_FKEY.getInverseKey());

        return _creditTransaction;
    }

    private transient StudentMartialArtPath _studentMartialArt;

    /**
     * Get the implicit to-many join path to the
     * <code>public.student_martial_art</code> table
     */
    public StudentMartialArtPath studentMartialArt() {
        if (_studentMartialArt == null)
            _studentMartialArt = new StudentMartialArtPath(this, null, Keys.STUDENT_MARTIAL_ART__STUDENT_MARTIAL_ART_MARTIAL_ART_ID_FKEY.getInverseKey());

        return _studentMartialArt;
    }

    private transient TrainingPath _training;

    /**
     * Get the implicit to-many join path to the <code>public.training</code>
     * table
     */
    public TrainingPath training() {
        if (_training == null)
            _training = new TrainingPath(this, null, Keys.TRAINING__TRAINING_MARTIAL_ART_ID_FKEY.getInverseKey());

        return _training;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.student</code> table
     */
    public StudentPath student() {
        return studentMartialArt().student();
    }

    @Override
    public List<Check<MartialArtRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("martial_art_program_type_check"), "(((program_type)::text = ANY ((ARRAY['CONTINUOUS'::character varying, 'COURSE'::character varying])::text[])))", true)
        );
    }

    @Override
    public MartialArt as(String alias) {
        return new MartialArt(DSL.name(alias), this);
    }

    @Override
    public MartialArt as(Name alias) {
        return new MartialArt(alias, this);
    }

    @Override
    public MartialArt as(Table<?> alias) {
        return new MartialArt(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MartialArt rename(String name) {
        return new MartialArt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MartialArt rename(Name name) {
        return new MartialArt(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MartialArt rename(Table<?> name) {
        return new MartialArt(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MartialArt where(Condition condition) {
        return new MartialArt(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MartialArt where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MartialArt where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MartialArt where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MartialArt where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MartialArt where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MartialArt where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MartialArt where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MartialArt whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MartialArt whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
