/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.Student.StudentPath;
import sk.emaa.model.entity.tables.Training.TrainingPath;
import sk.emaa.model.entity.tables.UserAccount.UserAccountPath;
import sk.emaa.model.entity.tables.records.SchoolRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class School extends TableImpl<SchoolRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.school</code>
     */
    public static final School SCHOOL = new School();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SchoolRecord> getRecordType() {
        return SchoolRecord.class;
    }

    /**
     * The column <code>public.school.id</code>.
     */
    public final TableField<SchoolRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.school.name</code>.
     */
    public final TableField<SchoolRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.school.address</code>.
     */
    public final TableField<SchoolRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(200), this, "");

    private School(Name alias, Table<SchoolRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private School(Name alias, Table<SchoolRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.school</code> table reference
     */
    public School(String alias) {
        this(DSL.name(alias), SCHOOL);
    }

    /**
     * Create an aliased <code>public.school</code> table reference
     */
    public School(Name alias) {
        this(alias, SCHOOL);
    }

    /**
     * Create a <code>public.school</code> table reference
     */
    public School() {
        this(DSL.name("school"), null);
    }

    public <O extends Record> School(Table<O> path, ForeignKey<O, SchoolRecord> childPath, InverseForeignKey<O, SchoolRecord> parentPath) {
        super(path, childPath, parentPath, SCHOOL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SchoolPath extends School implements Path<SchoolRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SchoolPath(Table<O> path, ForeignKey<O, SchoolRecord> childPath, InverseForeignKey<O, SchoolRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SchoolPath(Name alias, Table<SchoolRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SchoolPath as(String alias) {
            return new SchoolPath(DSL.name(alias), this);
        }

        @Override
        public SchoolPath as(Name alias) {
            return new SchoolPath(alias, this);
        }

        @Override
        public SchoolPath as(Table<?> alias) {
            return new SchoolPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SchoolRecord, Integer> getIdentity() {
        return (Identity<SchoolRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SchoolRecord> getPrimaryKey() {
        return Keys.SCHOOL_PKEY;
    }

    private transient StudentPath _student;

    /**
     * Get the implicit to-many join path to the <code>public.student</code>
     * table
     */
    public StudentPath student() {
        if (_student == null)
            _student = new StudentPath(this, null, Keys.STUDENT__STUDENT_SCHOOL_ID_FKEY.getInverseKey());

        return _student;
    }

    private transient TrainingPath _training;

    /**
     * Get the implicit to-many join path to the <code>public.training</code>
     * table
     */
    public TrainingPath training() {
        if (_training == null)
            _training = new TrainingPath(this, null, Keys.TRAINING__TRAINING_SCHOOL_ID_FKEY.getInverseKey());

        return _training;
    }

    private transient UserAccountPath _userAccount;

    /**
     * Get the implicit to-many join path to the
     * <code>public.user_account</code> table
     */
    public UserAccountPath userAccount() {
        if (_userAccount == null)
            _userAccount = new UserAccountPath(this, null, Keys.USER_ACCOUNT__USERS_SCHOOL_ID_FKEY.getInverseKey());

        return _userAccount;
    }

    @Override
    public School as(String alias) {
        return new School(DSL.name(alias), this);
    }

    @Override
    public School as(Name alias) {
        return new School(alias, this);
    }

    @Override
    public School as(Table<?> alias) {
        return new School(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public School rename(String name) {
        return new School(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public School rename(Name name) {
        return new School(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public School rename(Table<?> name) {
        return new School(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public School where(Condition condition) {
        return new School(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public School where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public School where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public School where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public School where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public School where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public School where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public School where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public School whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public School whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
