/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Indexes;
import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.MartialArt.MartialArtPath;
import sk.emaa.model.entity.tables.Student.StudentPath;
import sk.emaa.model.entity.tables.records.StudentMartialArtRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StudentMartialArt extends TableImpl<StudentMartialArtRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.student_martial_art</code>
     */
    public static final StudentMartialArt STUDENT_MARTIAL_ART = new StudentMartialArt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentMartialArtRecord> getRecordType() {
        return StudentMartialArtRecord.class;
    }

    /**
     * The column <code>public.student_martial_art.student_id</code>.
     */
    public final TableField<StudentMartialArtRecord, Integer> STUDENT_ID = createField(DSL.name("student_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.student_martial_art.martial_art_id</code>.
     */
    public final TableField<StudentMartialArtRecord, Integer> MARTIAL_ART_ID = createField(DSL.name("martial_art_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.student_martial_art.active</code>.
     */
    public final TableField<StudentMartialArtRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.student_martial_art.grade</code>.
     */
    public final TableField<StudentMartialArtRecord, Integer> GRADE = createField(DSL.name("grade"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.student_martial_art.base_payment_amount</code>.
     */
    public final TableField<StudentMartialArtRecord, Integer> BASE_PAYMENT_AMOUNT = createField(DSL.name("base_payment_amount"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.student_martial_art.payment_type</code>.
     */
    public final TableField<StudentMartialArtRecord, String> PAYMENT_TYPE = createField(DSL.name("payment_type"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.student_martial_art.credit</code>.
     */
    public final TableField<StudentMartialArtRecord, Integer> CREDIT = createField(DSL.name("credit"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private StudentMartialArt(Name alias, Table<StudentMartialArtRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StudentMartialArt(Name alias, Table<StudentMartialArtRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.student_martial_art</code> table reference
     */
    public StudentMartialArt(String alias) {
        this(DSL.name(alias), STUDENT_MARTIAL_ART);
    }

    /**
     * Create an aliased <code>public.student_martial_art</code> table reference
     */
    public StudentMartialArt(Name alias) {
        this(alias, STUDENT_MARTIAL_ART);
    }

    /**
     * Create a <code>public.student_martial_art</code> table reference
     */
    public StudentMartialArt() {
        this(DSL.name("student_martial_art"), null);
    }

    public <O extends Record> StudentMartialArt(Table<O> path, ForeignKey<O, StudentMartialArtRecord> childPath, InverseForeignKey<O, StudentMartialArtRecord> parentPath) {
        super(path, childPath, parentPath, STUDENT_MARTIAL_ART);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StudentMartialArtPath extends StudentMartialArt implements Path<StudentMartialArtRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StudentMartialArtPath(Table<O> path, ForeignKey<O, StudentMartialArtRecord> childPath, InverseForeignKey<O, StudentMartialArtRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StudentMartialArtPath(Name alias, Table<StudentMartialArtRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StudentMartialArtPath as(String alias) {
            return new StudentMartialArtPath(DSL.name(alias), this);
        }

        @Override
        public StudentMartialArtPath as(Name alias) {
            return new StudentMartialArtPath(alias, this);
        }

        @Override
        public StudentMartialArtPath as(Table<?> alias) {
            return new StudentMartialArtPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SMA_MARTIAL_ART, Indexes.IDX_SMA_STUDENT);
    }

    @Override
    public UniqueKey<StudentMartialArtRecord> getPrimaryKey() {
        return Keys.STUDENT_MARTIAL_ART_PKEY;
    }

    @Override
    public List<ForeignKey<StudentMartialArtRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STUDENT_MARTIAL_ART__STUDENT_MARTIAL_ART_MARTIAL_ART_ID_FKEY, Keys.STUDENT_MARTIAL_ART__STUDENT_MARTIAL_ART_STUDENT_ID_FKEY);
    }

    private transient MartialArtPath _martialArt;

    /**
     * Get the implicit join path to the <code>public.martial_art</code> table.
     */
    public MartialArtPath martialArt() {
        if (_martialArt == null)
            _martialArt = new MartialArtPath(this, Keys.STUDENT_MARTIAL_ART__STUDENT_MARTIAL_ART_MARTIAL_ART_ID_FKEY, null);

        return _martialArt;
    }

    private transient StudentPath _student;

    /**
     * Get the implicit join path to the <code>public.student</code> table.
     */
    public StudentPath student() {
        if (_student == null)
            _student = new StudentPath(this, Keys.STUDENT_MARTIAL_ART__STUDENT_MARTIAL_ART_STUDENT_ID_FKEY, null);

        return _student;
    }

    @Override
    public List<Check<StudentMartialArtRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("student_martial_art_payment_type_check"), "(((payment_type)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying, 'CREDIT'::character varying, 'NO_PAYMENT'::character varying])::text[])))", true)
        );
    }

    @Override
    public StudentMartialArt as(String alias) {
        return new StudentMartialArt(DSL.name(alias), this);
    }

    @Override
    public StudentMartialArt as(Name alias) {
        return new StudentMartialArt(alias, this);
    }

    @Override
    public StudentMartialArt as(Table<?> alias) {
        return new StudentMartialArt(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentMartialArt rename(String name) {
        return new StudentMartialArt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentMartialArt rename(Name name) {
        return new StudentMartialArt(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentMartialArt rename(Table<?> name) {
        return new StudentMartialArt(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentMartialArt where(Condition condition) {
        return new StudentMartialArt(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentMartialArt where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentMartialArt where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentMartialArt where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StudentMartialArt where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StudentMartialArt where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StudentMartialArt where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StudentMartialArt where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentMartialArt whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentMartialArt whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
