/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.Student.StudentPath;
import sk.emaa.model.entity.tables.records.StudentTypeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StudentType extends TableImpl<StudentTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.student_type</code>
     */
    public static final StudentType STUDENT_TYPE = new StudentType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentTypeRecord> getRecordType() {
        return StudentTypeRecord.class;
    }

    /**
     * The column <code>public.student_type.code</code>.
     */
    public final TableField<StudentTypeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.student_type.name</code>.
     */
    public final TableField<StudentTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50), this, "");

    private StudentType(Name alias, Table<StudentTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StudentType(Name alias, Table<StudentTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.student_type</code> table reference
     */
    public StudentType(String alias) {
        this(DSL.name(alias), STUDENT_TYPE);
    }

    /**
     * Create an aliased <code>public.student_type</code> table reference
     */
    public StudentType(Name alias) {
        this(alias, STUDENT_TYPE);
    }

    /**
     * Create a <code>public.student_type</code> table reference
     */
    public StudentType() {
        this(DSL.name("student_type"), null);
    }

    public <O extends Record> StudentType(Table<O> path, ForeignKey<O, StudentTypeRecord> childPath, InverseForeignKey<O, StudentTypeRecord> parentPath) {
        super(path, childPath, parentPath, STUDENT_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StudentTypePath extends StudentType implements Path<StudentTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StudentTypePath(Table<O> path, ForeignKey<O, StudentTypeRecord> childPath, InverseForeignKey<O, StudentTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StudentTypePath(Name alias, Table<StudentTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StudentTypePath as(String alias) {
            return new StudentTypePath(DSL.name(alias), this);
        }

        @Override
        public StudentTypePath as(Name alias) {
            return new StudentTypePath(alias, this);
        }

        @Override
        public StudentTypePath as(Table<?> alias) {
            return new StudentTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<StudentTypeRecord> getPrimaryKey() {
        return Keys.STUDENT_TYPE_PKEY;
    }

    private transient StudentPath _student;

    /**
     * Get the implicit to-many join path to the <code>public.student</code>
     * table
     */
    public StudentPath student() {
        if (_student == null)
            _student = new StudentPath(this, null, Keys.STUDENT__STUDENT_STUDENT_TYPE_FKEY.getInverseKey());

        return _student;
    }

    @Override
    public StudentType as(String alias) {
        return new StudentType(DSL.name(alias), this);
    }

    @Override
    public StudentType as(Name alias) {
        return new StudentType(alias, this);
    }

    @Override
    public StudentType as(Table<?> alias) {
        return new StudentType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentType rename(String name) {
        return new StudentType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentType rename(Name name) {
        return new StudentType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentType rename(Table<?> name) {
        return new StudentType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentType where(Condition condition) {
        return new StudentType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StudentType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StudentType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StudentType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StudentType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StudentType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
