/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.Attendance.AttendancePath;
import sk.emaa.model.entity.tables.School.SchoolPath;
import sk.emaa.model.entity.tables.records.StudentRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Student extends TableImpl<StudentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.student</code>
     */
    public static final Student STUDENT = new Student();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentRecord> getRecordType() {
        return StudentRecord.class;
    }

    /**
     * The column <code>public.student.id</code>.
     */
    public final TableField<StudentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.student.firstname</code>.
     */
    public final TableField<StudentRecord, String> FIRSTNAME = createField(DSL.name("firstname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.student.lastname</code>.
     */
    public final TableField<StudentRecord, String> LASTNAME = createField(DSL.name("lastname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.student.gender</code>.
     */
    public final TableField<StudentRecord, String> GENDER = createField(DSL.name("gender"), SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>public.student.id_card</code>.
     */
    public final TableField<StudentRecord, String> ID_CARD = createField(DSL.name("id_card"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.student.street</code>.
     */
    public final TableField<StudentRecord, String> STREET = createField(DSL.name("street"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.student.street_no</code>.
     */
    public final TableField<StudentRecord, String> STREET_NO = createField(DSL.name("street_no"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.student.city</code>.
     */
    public final TableField<StudentRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.student.zip</code>.
     */
    public final TableField<StudentRecord, String> ZIP = createField(DSL.name("zip"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.student.mobil</code>.
     */
    public final TableField<StudentRecord, String> MOBIL = createField(DSL.name("mobil"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.student.email</code>.
     */
    public final TableField<StudentRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.student.school_id</code>.
     */
    public final TableField<StudentRecord, Integer> SCHOOL_ID = createField(DSL.name("school_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.student.vegetarian</code>.
     */
    public final TableField<StudentRecord, Boolean> VEGETARIAN = createField(DSL.name("vegetarian"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.student.active</code>.
     */
    public final TableField<StudentRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.student.credit</code>.
     */
    public final TableField<StudentRecord, Integer> CREDIT = createField(DSL.name("credit"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private Student(Name alias, Table<StudentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Student(Name alias, Table<StudentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.student</code> table reference
     */
    public Student(String alias) {
        this(DSL.name(alias), STUDENT);
    }

    /**
     * Create an aliased <code>public.student</code> table reference
     */
    public Student(Name alias) {
        this(alias, STUDENT);
    }

    /**
     * Create a <code>public.student</code> table reference
     */
    public Student() {
        this(DSL.name("student"), null);
    }

    public <O extends Record> Student(Table<O> path, ForeignKey<O, StudentRecord> childPath, InverseForeignKey<O, StudentRecord> parentPath) {
        super(path, childPath, parentPath, STUDENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StudentPath extends Student implements Path<StudentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StudentPath(Table<O> path, ForeignKey<O, StudentRecord> childPath, InverseForeignKey<O, StudentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StudentPath(Name alias, Table<StudentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StudentPath as(String alias) {
            return new StudentPath(DSL.name(alias), this);
        }

        @Override
        public StudentPath as(Name alias) {
            return new StudentPath(alias, this);
        }

        @Override
        public StudentPath as(Table<?> alias) {
            return new StudentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<StudentRecord, Integer> getIdentity() {
        return (Identity<StudentRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<StudentRecord> getPrimaryKey() {
        return Keys.STUDENTS_PKEY;
    }

    @Override
    public List<ForeignKey<StudentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STUDENT__STUDENTS_SCHOOL_ID_FKEY);
    }

    private transient SchoolPath _school;

    /**
     * Get the implicit join path to the <code>public.school</code> table.
     */
    public SchoolPath school() {
        if (_school == null)
            _school = new SchoolPath(this, Keys.STUDENT__STUDENTS_SCHOOL_ID_FKEY, null);

        return _school;
    }

    private transient AttendancePath _attendance;

    /**
     * Get the implicit to-many join path to the <code>public.attendance</code>
     * table
     */
    public AttendancePath attendance() {
        if (_attendance == null)
            _attendance = new AttendancePath(this, null, Keys.ATTENDANCE__ATTENDANCES_STUDENT_ID_FKEY.getInverseKey());

        return _attendance;
    }

    @Override
    public Student as(String alias) {
        return new Student(DSL.name(alias), this);
    }

    @Override
    public Student as(Name alias) {
        return new Student(alias, this);
    }

    @Override
    public Student as(Table<?> alias) {
        return new Student(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Student rename(String name) {
        return new Student(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Student rename(Name name) {
        return new Student(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Student rename(Table<?> name) {
        return new Student(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student where(Condition condition) {
        return new Student(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Student where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Student where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Student where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Student where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
