/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.Attendance.AttendancePath;
import sk.emaa.model.entity.tables.CreditTransaction.CreditTransactionPath;
import sk.emaa.model.entity.tables.MartialArt.MartialArtPath;
import sk.emaa.model.entity.tables.School.SchoolPath;
import sk.emaa.model.entity.tables.StudentMartialArt.StudentMartialArtPath;
import sk.emaa.model.entity.tables.StudentType.StudentTypePath;
import sk.emaa.model.entity.tables.records.StudentRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Student extends TableImpl<StudentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.student</code>
     */
    public static final Student STUDENT = new Student();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentRecord> getRecordType() {
        return StudentRecord.class;
    }

    /**
     * The column <code>public.student.id</code>.
     */
    public final TableField<StudentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.student.firstname</code>.
     */
    public final TableField<StudentRecord, String> FIRSTNAME = createField(DSL.name("firstname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.student.lastname</code>.
     */
    public final TableField<StudentRecord, String> LASTNAME = createField(DSL.name("lastname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.student.gender</code>.
     */
    public final TableField<StudentRecord, String> GENDER = createField(DSL.name("gender"), SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>public.student.id_card</code>.
     */
    public final TableField<StudentRecord, String> ID_CARD = createField(DSL.name("id_card"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.student.street</code>.
     */
    public final TableField<StudentRecord, String> STREET = createField(DSL.name("street"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.student.street_no</code>.
     */
    public final TableField<StudentRecord, String> STREET_NO = createField(DSL.name("street_no"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.student.city</code>.
     */
    public final TableField<StudentRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.student.zip_code</code>.
     */
    public final TableField<StudentRecord, String> ZIP_CODE = createField(DSL.name("zip_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.student.mobil</code>.
     */
    public final TableField<StudentRecord, String> MOBIL = createField(DSL.name("mobil"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.student.email</code>.
     */
    public final TableField<StudentRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.student.school_id</code>.
     */
    public final TableField<StudentRecord, Integer> SCHOOL_ID = createField(DSL.name("school_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.student.vegetarian</code>.
     */
    public final TableField<StudentRecord, Boolean> VEGETARIAN = createField(DSL.name("vegetarian"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.student.gluten_free</code>.
     */
    public final TableField<StudentRecord, Boolean> GLUTEN_FREE = createField(DSL.name("gluten_free"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.student.active</code>.
     */
    public final TableField<StudentRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.student.credit</code>.
     */
    public final TableField<StudentRecord, Integer> CREDIT = createField(DSL.name("credit"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.student.payment_type</code>.
     */
    public final TableField<StudentRecord, String> PAYMENT_TYPE = createField(DSL.name("payment_type"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.student.base_payment_amount</code>.
     */
    public final TableField<StudentRecord, Integer> BASE_PAYMENT_AMOUNT = createField(DSL.name("base_payment_amount"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.student.grade</code>.
     */
    public final TableField<StudentRecord, Integer> GRADE = createField(DSL.name("grade"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.student.birthdate</code>.
     */
    public final TableField<StudentRecord, LocalDate> BIRTHDATE = createField(DSL.name("birthdate"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.student.created_at</code>.
     */
    public final TableField<StudentRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.student.national_id</code>.
     */
    public final TableField<StudentRecord, String> NATIONAL_ID = createField(DSL.name("national_id"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.student.student_type</code>.
     */
    public final TableField<StudentRecord, String> STUDENT_TYPE = createField(DSL.name("student_type"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("'STUDENT'::character varying"), SQLDataType.VARCHAR)), this, "");

    private Student(Name alias, Table<StudentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Student(Name alias, Table<StudentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.student</code> table reference
     */
    public Student(String alias) {
        this(DSL.name(alias), STUDENT);
    }

    /**
     * Create an aliased <code>public.student</code> table reference
     */
    public Student(Name alias) {
        this(alias, STUDENT);
    }

    /**
     * Create a <code>public.student</code> table reference
     */
    public Student() {
        this(DSL.name("student"), null);
    }

    public <O extends Record> Student(Table<O> path, ForeignKey<O, StudentRecord> childPath, InverseForeignKey<O, StudentRecord> parentPath) {
        super(path, childPath, parentPath, STUDENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StudentPath extends Student implements Path<StudentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StudentPath(Table<O> path, ForeignKey<O, StudentRecord> childPath, InverseForeignKey<O, StudentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StudentPath(Name alias, Table<StudentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StudentPath as(String alias) {
            return new StudentPath(DSL.name(alias), this);
        }

        @Override
        public StudentPath as(Name alias) {
            return new StudentPath(alias, this);
        }

        @Override
        public StudentPath as(Table<?> alias) {
            return new StudentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<StudentRecord, Integer> getIdentity() {
        return (Identity<StudentRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<StudentRecord> getPrimaryKey() {
        return Keys.STUDENT_PKEY;
    }

    @Override
    public List<ForeignKey<StudentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STUDENT__STUDENT_SCHOOL_ID_FKEY, Keys.STUDENT__STUDENT_STUDENT_TYPE_FKEY);
    }

    private transient SchoolPath _school;

    /**
     * Get the implicit join path to the <code>public.school</code> table.
     */
    public SchoolPath school() {
        if (_school == null)
            _school = new SchoolPath(this, Keys.STUDENT__STUDENT_SCHOOL_ID_FKEY, null);

        return _school;
    }

    private transient StudentTypePath _studentType;

    /**
     * Get the implicit join path to the <code>public.student_type</code> table.
     */
    public StudentTypePath studentType() {
        if (_studentType == null)
            _studentType = new StudentTypePath(this, Keys.STUDENT__STUDENT_STUDENT_TYPE_FKEY, null);

        return _studentType;
    }

    private transient AttendancePath _attendance;

    /**
     * Get the implicit to-many join path to the <code>public.attendance</code>
     * table
     */
    public AttendancePath attendance() {
        if (_attendance == null)
            _attendance = new AttendancePath(this, null, Keys.ATTENDANCE__ATTENDANCE_STUDENT_ID_FKEY.getInverseKey());

        return _attendance;
    }

    private transient CreditTransactionPath _creditTransaction;

    /**
     * Get the implicit to-many join path to the
     * <code>public.credit_transaction</code> table
     */
    public CreditTransactionPath creditTransaction() {
        if (_creditTransaction == null)
            _creditTransaction = new CreditTransactionPath(this, null, Keys.CREDIT_TRANSACTION__CREDIT_TRANSACTION_STUDENT_ID_FKEY.getInverseKey());

        return _creditTransaction;
    }

    private transient StudentMartialArtPath _studentMartialArt;

    /**
     * Get the implicit to-many join path to the
     * <code>public.student_martial_art</code> table
     */
    public StudentMartialArtPath studentMartialArt() {
        if (_studentMartialArt == null)
            _studentMartialArt = new StudentMartialArtPath(this, null, Keys.STUDENT_MARTIAL_ART__STUDENT_MARTIAL_ART_STUDENT_ID_FKEY.getInverseKey());

        return _studentMartialArt;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.martial_art</code> table
     */
    public MartialArtPath martialArt() {
        return studentMartialArt().martialArt();
    }

    @Override
    public List<Check<StudentRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("student_payment_type_check"), "(((payment_type)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying, 'CREDIT'::character varying, 'NO_PAYMENT'::character varying])::text[])))", true)
        );
    }

    @Override
    public Student as(String alias) {
        return new Student(DSL.name(alias), this);
    }

    @Override
    public Student as(Name alias) {
        return new Student(alias, this);
    }

    @Override
    public Student as(Table<?> alias) {
        return new Student(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Student rename(String name) {
        return new Student(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Student rename(Name name) {
        return new Student(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Student rename(Table<?> name) {
        return new Student(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student where(Condition condition) {
        return new Student(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Student where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Student where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Student where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Student where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Student whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
