/*
 * This file is generated by jOOQ.
 */
package sk.emaa.model.entity.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.emaa.model.entity.Keys;
import sk.emaa.model.entity.Public;
import sk.emaa.model.entity.tables.Attendance.AttendancePath;
import sk.emaa.model.entity.tables.CreditTransaction.CreditTransactionPath;
import sk.emaa.model.entity.tables.School.SchoolPath;
import sk.emaa.model.entity.tables.records.TrainingRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Training extends TableImpl<TrainingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.training</code>
     */
    public static final Training TRAINING = new Training();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrainingRecord> getRecordType() {
        return TrainingRecord.class;
    }

    /**
     * The column <code>public.training.id</code>.
     */
    public final TableField<TrainingRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.training.date</code>.
     */
    public final TableField<TrainingRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.training.school_id</code>.
     */
    public final TableField<TrainingRecord, Integer> SCHOOL_ID = createField(DSL.name("school_id"), SQLDataType.INTEGER, this, "");

    private Training(Name alias, Table<TrainingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Training(Name alias, Table<TrainingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.training</code> table reference
     */
    public Training(String alias) {
        this(DSL.name(alias), TRAINING);
    }

    /**
     * Create an aliased <code>public.training</code> table reference
     */
    public Training(Name alias) {
        this(alias, TRAINING);
    }

    /**
     * Create a <code>public.training</code> table reference
     */
    public Training() {
        this(DSL.name("training"), null);
    }

    public <O extends Record> Training(Table<O> path, ForeignKey<O, TrainingRecord> childPath, InverseForeignKey<O, TrainingRecord> parentPath) {
        super(path, childPath, parentPath, TRAINING);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrainingPath extends Training implements Path<TrainingRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrainingPath(Table<O> path, ForeignKey<O, TrainingRecord> childPath, InverseForeignKey<O, TrainingRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrainingPath(Name alias, Table<TrainingRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrainingPath as(String alias) {
            return new TrainingPath(DSL.name(alias), this);
        }

        @Override
        public TrainingPath as(Name alias) {
            return new TrainingPath(alias, this);
        }

        @Override
        public TrainingPath as(Table<?> alias) {
            return new TrainingPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TrainingRecord, Integer> getIdentity() {
        return (Identity<TrainingRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TrainingRecord> getPrimaryKey() {
        return Keys.TRAINING_PKEY;
    }

    @Override
    public List<ForeignKey<TrainingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRAINING__TRAINING_SCHOOL_ID_FKEY);
    }

    private transient SchoolPath _school;

    /**
     * Get the implicit join path to the <code>public.school</code> table.
     */
    public SchoolPath school() {
        if (_school == null)
            _school = new SchoolPath(this, Keys.TRAINING__TRAINING_SCHOOL_ID_FKEY, null);

        return _school;
    }

    private transient AttendancePath _attendance;

    /**
     * Get the implicit to-many join path to the <code>public.attendance</code>
     * table
     */
    public AttendancePath attendance() {
        if (_attendance == null)
            _attendance = new AttendancePath(this, null, Keys.ATTENDANCE__ATTENDANCE_TRAINING_ID_FKEY.getInverseKey());

        return _attendance;
    }

    private transient CreditTransactionPath _creditTransaction;

    /**
     * Get the implicit to-many join path to the
     * <code>public.credit_transaction</code> table
     */
    public CreditTransactionPath creditTransaction() {
        if (_creditTransaction == null)
            _creditTransaction = new CreditTransactionPath(this, null, Keys.CREDIT_TRANSACTION__CREDIT_TRANSACTION_TRAINING_ID_FKEY.getInverseKey());

        return _creditTransaction;
    }

    @Override
    public Training as(String alias) {
        return new Training(DSL.name(alias), this);
    }

    @Override
    public Training as(Name alias) {
        return new Training(alias, this);
    }

    @Override
    public Training as(Table<?> alias) {
        return new Training(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Training rename(String name) {
        return new Training(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Training rename(Name name) {
        return new Training(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Training rename(Table<?> name) {
        return new Training(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Training where(Condition condition) {
        return new Training(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Training where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Training where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Training where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Training where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Training where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Training where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Training where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Training whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Training whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
